apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-repo-config
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/gyanavardhana/Argo-cd.git
      username: gyanavardhana
      password: ############
