version: '3.8'

services:
  web:
    build: gyanavardhan/fortask:dockertask
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - ./pgdata:/var/lib/postgresql/data
