apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gyanavardhan/fortask:dockertask
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "default"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "myapp_development"
        - name: POSTGRES_HOST
          value: "db"
